apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-controller
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-controller-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-controller-rolebinding
subjects:
- kind: ServiceAccount
  name: resource-controller
  namespace: default
roleRef:
  kind: ClusterRole
  name: resource-controller-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: resourcereserve-controller-deployment
  labels:
    app: resourcereserve-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resourcereserve-controller
  template:
    metadata:
      labels:
        app: resourcereserve-controller
    spec:
      serviceAccountName: resourcereserve-controller
      containers:
      - name: resourcereserve-controller
        image: registry.cn-hangzhou.aliyuncs.com/zsj-dev/resource-controller:v0.0.1
        imagePullPolicy: Always